export const SET_CITY = 'WEATHER::SET_CITY';
export const SET_WEATHER_LIST = 'WATHER::SET_WEATHER_LIST';
export const SET_INFORMATION_CITY = 'WATHER::INFORMATION_CITY';
export const SHOW_ALERT = 'SHOW_ALERT';
export const ADD_FAVORITES = 'ADD_FAVORITES';
export const REMOVE_FAVORITES = 'REMOVE_FAVORITES';